### ISSUE TITLE
그... 이상해요. 내용 보세요

### ISSUE THREAD

**Issue by ghost** [Preta-Crowz/Prj_KT#20]
제가 server-install.bat을 실행하고 sv1.bat인가 그거 실행하고 web.bat을 실행했는데 web.bat이 일케 말해요.

[2020-05-30 09:03:25] << KKuTu Web >>
[2020-05-30 09:03:25] << KKuTu Web >>
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (D:\.럭키끄투\KKuTu-Priv-Prj_KT\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34)
    at new Strategy (D:\.럭키끄투\KKuTu-Priv-Prj_KT\Server\lib\node_modules\passport-amazon\lib\strategy.js:48:18)
    at D:\.럭키끄투\KKuTu-Priv-Prj_KT\Server\lib\Web\routes\login.js:75:26
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (D:\.럭키끄투\KKuTu-Priv-Prj_KT\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34)
    at new Strategy (D:\.럭키끄투\KKuTu-Priv-Prj_KT\Server\lib\node_modules\passport-amazon\lib\strategy.js:48:18)
    at D:\.럭키끄투\KKuTu-Priv-Prj_KT\Server\lib\Web\routes\login.js:75:26
[2020-05-30 09:03:26] Game server #2 connected
[2020-05-30 09:03:26] Game server #1 connected
[2020-05-30 09:03:26] DB is ready.
[2020-05-30 09:03:27] DB is ready.

겁나 쏼라쏼라

**Comment by ghost** [comment]
@Preta-Crowz

**Comment by Preta-Crowz** [comment]
로그인 관련 json파일을 설정하여야합니다. 사용하지 않는 로그인의 경우 js파일의 이름을 변경하여 인식되지 않도록 해주세요.

**Comment by ghost** [comment]
그리고
[2020-05-30 10:32:03] [36m&lt;&lt; KKuTu Server:8913 >>[39m
[2020-05-30 10:32:03] [36m&lt;&lt; KKuTu Server:8914 >>[39m
[2020-05-30 10:32:03] [36m&lt;&lt; KKuTu Server:8913 >>[39m
[2020-05-30 10:32:03] [36m&lt;&lt; KKuTu Server:8912 >>[39m
[2020-05-30 10:32:03] [36m&lt;&lt; KKuTu Server:8914 >>[39m
[2020-05-30 10:32:04] [36m&lt;&lt; KKuTu Server:8915 >>[39m
[2020-05-30 10:32:04] [43m[30mError on ws: Error: bind EADDRINUSE 0.0.0.0:8913[39m[49m
[2020-05-30 10:32:04] [43m[30mError on ws: Error: bind EADDRINUSE 0.0.0.0:8914[39m[49m
[2020-05-30 10:32:04] [36m&lt;&lt; KKuTu Server:8498 >>[39m
[2020-05-30 10:32:04] [36m&lt;&lt; KKuTu Server:8496 >>[39m
[2020-05-30 10:32:04] [36m&lt;&lt; KKuTu Server:8497 >>[39m
[2020-05-30 10:32:05] [36m&lt;&lt; KKuTu Web >>[39m
[2020-05-30 10:32:05] [36m&lt;&lt; KKuTu Web >>[39m
[2020-05-30 10:32:05] [36m&lt;&lt; KKuTu Web >>[39m
[2020-05-30 10:32:05] [32mMaster DB is ready.[39m
[2020-05-30 10:32:05] [32mDB is ready.[39m
[2020-05-30 10:32:05] [32mDB is ready.[39m
[2020-05-30 10:32:05] [32mDB is ready.[39m
[2020-05-30 10:32:05] [32mDB is ready.[39m
[2020-05-30 10:32:05] [32mDB is ready.[39m
[2020-05-30 10:32:05] [32mDB is ready.[39m
[2020-05-30 10:32:05] [32mMaster DB is ready.[39m
[2020-05-30 10:32:05] [32mDB is ready.[39m
[2020-05-30 10:32:05] [32mMaster DB is ready.[39m
[2020-05-30 10:32:06] [32mDB is ready.[39m
[2020-05-30 10:32:06] [32mDB is ready.[39m
[2020-05-30 10:32:06] [43m[30mError on ws: Error: listen EADDRINUSE: address already in use 0.0.0.0:8496[39m[49m
[2020-05-30 10:32:06] [43m[30mError on ws: Error: listen EADDRINUSE: address already in use 0.0.0.0:8497[39m[49m
[2020-05-30 10:32:27] [43m[30mWrong channel value undefined on @2[39m[49m [2020-05-30 10:32:27] [43m[30mWrong channel value undefined on @2[39m[49m [2020-05-30 10:32:27] [43m[30mWrong channel value undefined on @2[39m[49m [2020-05-30 10:32:27] [36mNew web server #3[39m [2020-05-30 10:32:27] [36mNew web server #1[39m [2020-05-30 10:32:27] [36mNew web server #2[39m
[2020-05-30 10:32:27] [43m[30mWrong channel value undefined on @2[39m[49m [2020-05-30 10:32:27] [43m[30mWrong channel value undefined on @2[39m[49m [2020-05-30 10:32:27] [43m[30mWrong channel value undefined on @2[39m[49m
[2020-05-30 10:32:27] [36mGame server #1 connected[39m [2020-05-30 10:32:27] [36mGame server #1 connected[39m [2020-05-30 10:32:27] [36mGame server #1 connected[39m [2020-05-30 10:32:27] [41mGame server #1 closed: 1000[49m [2020-05-30 10:32:27] [41mGame server #1 closed: 1000[49m [2020-05-30 10:32:27] [36mGame server #3 connected[39m [2020-05-30 10:32:27] [36mGame server #3 connected[39m [2020-05-30 10:32:27] [36mGame server #3 connected[39m [2020-05-30 10:32:27] [41mGame server #3 closed: 1000[49m [2020-05-30 10:32:27] [36mGame server #3 connected[39m [2020-05-30 10:32:27] [41mGame server #3 closed: 1000[49m [2020-05-30 10:32:27] [36mGame server #2 connected[39m [2020-05-30 10:32:27] [41mGame server #2 closed: 1000[49m [2020-05-30 10:32:27] [41mGame server #3 closed: 1000[49m [2020-05-30 10:32:27] [36mGame server #2 connected[39m [2020-05-30 10:32:27] [36mGame server #2 connected[39m [2020-05-30 10:32:27] [36mGame server #2 connected[39m [2020-05-30 10:32:27] [41mGame server #2 closed: 1000[49m [2020-05-30 10:32:27] [41mGame server #2 closed: 1000[49m [2020-05-30 10:32:27] [36mGame server #1 connected[39m [2020-05-30 10:32:27] [41mGame server #1 closed: 1000[49m [2020-05-30 10:32:27] [32mDB is ready.[39m [2020-05-30 10:32:27] [32mDB is ready.[39m [2020-05-30 10:32:27] [32mDB is ready.[39m
[2020-05-30 10:32:27] [43m[30mWrong channel value undefined on @1[39m[49m [2020-05-30 10:32:27] [43m[30mWrong channel value undefined on @1[39m[49m [2020-05-30 10:32:27] [43m[30mWrong channel value undefined on @1[39m[49m
[2020-05-30 10:32:43] [41mGame server #2 closed: 1006[49m [2020-05-30 10:32:43] [41mGame server #3 closed: 1006[49m [2020-05-30 10:32:43] [41mGame server #1 closed: 1006[49m
G: CLOSED WITH CODE null
G: CLOSED WITH CODE null
W: CLOSED WITH CODE null
G: CLOSED WITH CODE null
[2020-05-30 10:32:51] [36m&lt;&lt; KKuTu Server:8913 >>[39m
[2020-05-30 10:32:51] [36m&lt;&lt; KKuTu Server:8914 >>[39m
[2020-05-30 10:32:51] [36m&lt;&lt; KKuTu Server:8915 >>[39m
[2020-05-30 10:32:51] [36m&lt;&lt; KKuTu Server:8913 >>[39m
[2020-05-30 10:32:51] [43m[30mError on ws: Error: bind EADDRINUSE 0.0.0.0:8913[39m[49m
[2020-05-30 10:32:51] [36m&lt;&lt; KKuTu Server:8914 >>[39m
[2020-05-30 10:32:52] [36m&lt;&lt; KKuTu Server:8912 >>[39m
[2020-05-30 10:32:52] [36m&lt;&lt; KKuTu Server:8498 >>[39m
[2020-05-30 10:32:52] [36m&lt;&lt; KKuTu Server:8496 >>[39m
[2020-05-30 10:32:52] [36m&lt;&lt; KKuTu Server:8497 >>[39m
[2020-05-30 10:32:52] [43m[30mError on ws: Error: bind EADDRINUSE 0.0.0.0:8914[39m[49m
[2020-05-30 10:32:52] [32mMaster DB is ready.[39m
[2020-05-30 10:32:52] [32mDB is ready.[39m
[2020-05-30 10:32:52] [43m[30mError on ws: Error: listen EADDRINUSE: address already in use 0.0.0.0:8497[39m[49m
[2020-05-30 10:32:52] [36m&lt;&lt; KKuTu Web >>[39m
[2020-05-30 10:32:52] [36m&lt;&lt; KKuTu Web >>[39m
[2020-05-30 10:32:52] [36m&lt;&lt; KKuTu Web >>[39m
[2020-05-30 10:32:53] [32mDB is ready.[39m
[2020-05-30 10:32:53] [32mMaster DB is ready.[39m
[2020-05-30 10:32:53] [32mDB is ready.[39m
[2020-05-30 10:32:53] [32mDB is ready.[39m
[2020-05-30 10:32:53] [32mMaster DB is ready.[39m
[2020-05-30 10:32:53] [43m[30mError on ws: Error: listen EADDRINUSE: address already in use 0.0.0.0:8496[39m[49m
[2020-05-30 10:32:53] [32mDB is ready.[39m
[2020-05-30 10:32:53] [32mDB is ready.[39m
[2020-05-30 10:32:53] [32mDB is ready.[39m
[2020-05-30 10:32:54] [32mDB is ready.[39m
[2020-05-30 10:32:54] [32mDB is ready.[39m
[2020-05-30 10:33:15] [36mNew web server #1[39m [2020-05-30 10:33:15] [36mNew web server #3[39m [2020-05-30 10:33:15] [36mNew web server #2[39m [2020-05-30 10:33:15] [43m[30mWrong channel value undefined on @2[39m[49m [2020-05-30 10:33:15] [43m[30mWrong channel value undefined on @1[39m[49m [2020-05-30 10:33:15] [43m[30mWrong channel value undefined on @1[39m[49m [2020-05-30 10:33:15] [43m[30mWrong channel value undefined on @1[39m[49m [2020-05-30 10:33:15] [43m[30mWrong channel value undefined on @2[39m[49m [2020-05-30 10:33:15] [43m[30mWrong channel value undefined on @2[39m[49m
[2020-05-30 10:33:15] [36mGame server #3 connected[39m [2020-05-30 10:33:15] [36mGame server #1 connected[39m [2020-05-30 10:33:15] [36mGame server #2 connected[39m [2020-05-30 10:33:15] [36mGame server #2 connected[39m [2020-05-30 10:33:15] [36mGame server #3 connected[39m [2020-05-30 10:33:15] [36mGame server #3 connected[39m [2020-05-30 10:33:16] [36mGame server #1 connected[39m [2020-05-30 10:33:16] [36mGame server #1 connected[39m [2020-05-30 10:33:16] [36mGame server #3 connected[39m [2020-05-30 10:33:16] [36mGame server #1 connected[39m [2020-05-30 10:33:16] [41mGame server #1 closed: 1000[49m [2020-05-30 10:33:16] [41mGame server #2 closed: 1000[49m [2020-05-30 10:33:16] [41mGame server #1 closed: 1000[49m [2020-05-30 10:33:16] [41mGame server #3 closed: 1000[49m [2020-05-30 10:33:16] [41mGame server #3 closed: 1000[49m [2020-05-30 10:33:16] [36mGame server #2 connected[39m [2020-05-30 10:33:16] [41mGame server #1 closed: 1000[49m [2020-05-30 10:33:16] [41mGame server #3 closed: 1000[49m [2020-05-30 10:33:16] [36mGame server #2 connected[39m [2020-05-30 10:33:16] [41mGame server #2 closed: 1000[49m [2020-05-30 10:33:16] [41mGame server #2 closed: 1000[49m [2020-05-30 10:33:16] [32mDB is ready.[39m [2020-05-30 10:33:16] [32mDB is ready.[39m
[2020-05-30 10:33:15] [43m[30mWrong channel value undefined on @2[39m[49m [2020-05-30 10:33:15] [43m[30mWrong channel value undefined on @2[39m[49m [2020-05-30 10:33:15] [43m[30mWrong channel value undefined on @2[39m[49m
[2020-05-30 10:33:16] [32mDB is ready.[39m

이건 run.bat이고요

[2020-05-30 10:43:19] << KKuTu Server:8496 >>
[2020-05-30 10:43:19] << KKuTu Server:8497 >>
[2020-05-30 10:43:20] Error on ws: Error: bind EADDRINUSE 0.0.0.0:8497
[2020-05-30 10:43:20] Error on ws: Error: bind EADDRINUSE 0.0.0.0:8496
[2020-05-30 10:43:20] Master DB is ready.
[2020-05-30 10:43:20] DB is ready.
[2020-05-30 10:43:20] DB is ready.
[2020-05-30 10:43:20] Error on ws: Error: listen EADDRINUSE: address already in use 0.0.0.0:8080

이건 sv0.bat

[2020-05-30 10:43:48] << KKuTu Web >>
[2020-05-30 10:43:48] << KKuTu Web >>
[2020-05-30 10:43:59] Game server #1 connected
[2020-05-30 10:44:01] Game server #1 connected
[2020-05-30 10:44:01] Game server #1 connected
[2020-05-30 10:44:01] Game server #1 connected
[2020-05-30 10:44:01] Game server #2 connected
[2020-05-30 10:44:01] Game server #2 connected
[2020-05-30 10:44:01] Game server #2 connected
[2020-05-30 10:44:01] Game server #2 closed: 1000
[2020-05-30 10:44:01] Game server #2 closed: 1000
[2020-05-30 10:44:01] Game server #2 connected
[2020-05-30 10:44:01] Game server #1 closed: 1000
[2020-05-30 10:44:01] Game server #1 closed: 1000
[2020-05-30 10:44:01] Game server #2 closed: 1000
[2020-05-30 10:44:01] Game server #1 closed: 1000
[2020-05-30 10:44:01] DB is ready.
[2020-05-30 10:44:01] DB is ready.

이건 web.bat입니다.
포트포워딩은 
사진처럼 했습니다.
![image](https://user-images.githubusercontent.com/63226197/83316744-a65f9c80-a262-11ea-949b-d23344e47584.png)

링크^^
이래요 ㅠㅗㅠ

**Comment by Preta-Crowz** [comment]
제 기억이 맞다면 제 레포지토리는 PC에 공인아이피를 직접 할당하는 경우를 생각하고 만든 것으로, 사설 아이피에서 정상 동작이 되지 않을 수 있습니다.

**Comment by ghost** [comment]
흙흙 안되구나... 
![image](https://user-images.githubusercontent.com/63226197/83318212-8aadc380-a26d-11ea-94d8-feec00ccb87a.png)
이 말로만 보던것도 나왔네...
